image: mcr.microsoft.com/dotnet/sdk:5.0-alpine

variables:
  BUILD_FOLDER: SimpleTrading.Candles.HttpServer
  DOCKER_IMAGE_TAG: monfex/simple-trading-candles-api

include:
  - project: 'MONFEX-DEVOPS/infrastructure_builder'
    ref: master
    file: '/.gitlab-ci.yml'